apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: producer
  namespace: kafka
  labels:
    app: producer
spec:
  selector:
    matchLabels:
      app: producer
      monitor-patient-data: "true"
  template:
    metadata:
      labels:
        app: producer
        monitor-patient-data: "true"
    spec:
      nodeSelector:
        monitor-patient-data: "true"
      containers:
      - name: producer
        image: reh69113/masterthesis:producer
        imagePullPolicy: Always
        env:
        - name: SERVER
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: TOPIC
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODENAME
          value: "testcluster-worker"
        - name: PROD
          value: "true"
        - name: CHECKEVERYTHING
          value: "true"
          #valueFrom:
          #  fieldRef:
              #pod name
          #    fieldPath: metadata.name
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - name: data
            mountPath: /app/data
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          hostPath:
            path: /tmp/data