apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: filter
  namespace: kafka
  labels:
    app: filter
spec:
  selector:
    matchLabels:
      app: filter
  serviceName: "filter"
  #Number must match amount of labeles nodes.
  replicas: 7
  template:
    metadata:
      labels:
        app: filter
    spec:
      containers:
      - name: filter
        image: reh69113/masterthesis:filter
        imagePullPolicy: Always
        env:
        - name: SERVER
          value: "kafka-0.kafka.kafka.svc.cluster.local:9092,kafka-1.kafka.kafka.svc.cluster.local:9092,kafka-2.kafka.kafka.svc.cluster.local:9092,kafka-4.kafka.kafka.svc.cluster.local:9092,kafka-5.kafka.kafka.svc.cluster.local:9092"
        - name: TOPIC
          valueFrom:
            fieldRef:
              #pod name
              fieldPath: metadata.name
        - name: NODENAME
          value: "filter-"